Description: "Create CodeBuild Projects"

Parameters: 
  networkStackName:
    Description: Name of the base stack with all network resources
    Type: String
    Default: nw

  permStackName:
    Description: Name of the base stack with all network resources
    Type: String
    Default: perm

  environment: 
    Type: String 
    Default: dev 
    AllowedValues: 
      - dev
      - prod 

Resources:
  codebuildBucket:
    Description: "Create S3 bucket for storing codebuild artifacts"
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ["-", [!Sub '{{resolve:ssm:/${environment}/codebuild/bucket_prefix}}', !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]] ]]
      
      Tags:
       - Key: Name
         Value: !Join [" - ", [Fn::Sub: "${AWS::StackName}", "bucket "] ]
       - Key: Environment
         Value: !Sub ${environment}	
  
  gitCreds:
    Type: AWS::CodeBuild::SourceCredential
    Properties:
        AuthType: '{{resolve:secretsmanager:git_creds:SecretString:auth_type}}'
        ServerType: '{{resolve:secretsmanager:git_creds:SecretString:server_type}}'
        Token: '{{resolve:secretsmanager:git_creds:SecretString:token}}'
        Username: '{{resolve:secretsmanager:git_creds:SecretString:username}}'
      
Outputs:
  BucketName:
    Value: !Ref codebuildBucket
    Export:
      "Name" :
        Fn::Sub: "${AWS::StackName}-CODEBUILD-BUCKET"

